# Modules
- color: "fbca04"
  description: "This issue or pull request is related to access-grants-instance module."
  name: ":floppy_disk: access-grants-instance"
- color: "fbca04"
  description: "This issue or pull request is related to access-point module."
  name: ":floppy_disk: access-point"
- color: "fbca04"
  description: "This issue or pull request is related to bucket module."
  name: ":floppy_disk: bucket"
- color: "fbca04"
  description: "This issue or pull request is related to objects module."
  name: ":floppy_disk: objects"
- color: "fbca04"
  description: "This issue or pull request is related to table module."
  name: ":floppy_disk: table"
- color: "fbca04"
  description: "This issue or pull request is related to table-bucket module."
  name: ":floppy_disk: table-bucket"
- color: "fbca04"
  description: "This issue or pull request is related to vector-bucket module."
  name: ":floppy_disk: vector-bucket"
