# Modules
":floppy_disk: access-grant":
- changed-files:
  - any-glob-to-any-file:
    - modules/access-grant/**/*

":floppy_disk: access-grants-instance":
- changed-files:
  - any-glob-to-any-file:
    - modules/access-grants-instance/**/*

":floppy_disk: access-grants-location":
- changed-files:
  - any-glob-to-any-file:
    - modules/access-grants-location/**/*

":floppy_disk: access-point":
- changed-files:
  - any-glob-to-any-file:
    - modules/access-point/**/*

":floppy_disk: bucket":
- changed-files:
  - any-glob-to-any-file:
    - modules/bucket/**/*

":floppy_disk: objects":
- changed-files:
  - any-glob-to-any-file:
    - modules/objects/**/*

":floppy_disk: table":
- changed-files:
  - any-glob-to-any-file:
    - modules/table/**/*

":floppy_disk: table-bucket":
- changed-files:
  - any-glob-to-any-file:
    - modules/table-bucket/**/*

":floppy_disk: vector-bucket":
- changed-files:
  - any-glob-to-any-file:
    - modules/vector-bucket/**/*
